apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lorawan-service
  labels:
    cloud.googleapis.com/location: europe-west4
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 101756015094-compute@developer.gserviceaccount.com
      containers:
        - image: ryzhasmomentas27/sep4xg5cloud:lorawan-service
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: mongodb_url
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: mongodb_url
            - name: lorawan_EUI_dev
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: lorawan_EUI-dev
            - name: lorawan_url
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: lorawan_url
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true