name: Build and Deploy to Google Cloud - App Engine

on:
  push:
    branches: [ "deployment-support" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy the application to App Engine
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate into Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.GC_WIF_PROVIDER }}
          service_account: ${{ secrets.GC_SERVICE_ACCOUNT }}

      - id: java
        name: Set up Java Environment (JDK 17 & Maven)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - id: deploy
        name: Deploy to App Engine
        run: mvn --batch-mode clean package appengine:deploy --file pom.xml
