name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build:
    name: My First Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Continuous Integration"
      