name: Test the Java Application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  maven-test:
    name: Test the Application with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v3

      - name: Set up Java Environment (JDK 17 & Maven)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Package the app and run tests with Maven Surefire Plugin
        run: mvn --batch-mode --fail-at-end test --file pom.xml
